sudo: false
language: go
go:
- '1.10'

install:
- go get -t
- go get github.com/mattn/goveralls

script:
- go tool vet . ./cmd
- go test -v -race
- go test -covermode=count -coverprofile=coverage.out .
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
- go build cmd/httpclient-gen-go/main.go

branches:
  only:
  - master

matrix:
  fast_finish: true
