// Code generated by client-gen-go; DO NOT EDIT.
// This file was generated by robots at
// 2020-10-23 10:46:35.888756713 +0200 CEST m=+0.001258310

package jsonplaceholder

import "github.com/postfinance/httpclient"

// Client is a generated wrapper for a http client and detected services.
type Client struct {
	*httpclient.Client

	// Services used for communicating with the API
	Post PostService
}

// NewClient returns a new API client.
func NewClient(baseURL string, opts ...httpclient.Opt) (*Client, error) {

	client, err := httpclient.New(baseURL, opts...)
	if err != nil {
		return nil, err
	}

	// services
	post := &PostImpl{client: client}

	return &Client{
		client,
		post,
	}, nil
}
